name: Test in Docker
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    # Cypress Docker image from https://hub.docker.com/r/cypress
    # with browsers pre-installed
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - run:  yarn set version berry
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
